version: '3.9'
services:
  db:
    image: mysql:8.3.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: rest_with_spring_boot
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3306
    ports:
      - "3306:3306"  
    expose:
      - 3306
    networks:
      - dev-network
  springboot_react_mysql:
    image: renandocker123/springboot_react_mysql
    restart: always
    build: .server/springboot_react_mysql
    working_dir: /springboot_react_mysql
    environment:
      TZ: America/Sao_Paulo
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3308/rest_with_spring_boot?useTimezone=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin123
    ports:
      - "80:80"
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
        - dev-network       

networks:
  dev-network:
    driver: bridge