name: Continuous Integration with Github Actions

on:
  push:
    branches:
      - docker-react-server

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [21]
        node-version: [20]

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    - name: Install Dependencies and Build
      working-directory: ./springboot_react_mysql/client
      run: | 
        npm install
        npm run build --if-present
    
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
        cache: maven

    - name: Build Application JAR
      working-directory: ./springboot_react_mysql/server
      run: mvn clean package
  
    - name: Docker Compose Build
      working-directory: ./
      run: docker compose build

    - name: Push backend image Docker to Hub Container Registry
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/springboot_backend_mysql:latest ${{ secrets.DOCKER_USERNAME }}/springboot_backend_mysql:${{ github.run_id }}

        docker push ${{ secrets.DOCKER_USERNAME }}/springboot_backend_mysql:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/springboot_backend_mysql:latest

    - name: Push frontend image Docker to Hub Container Registry
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/springboot_react_app:latest ${{ secrets.DOCKER_USERNAME }}/springboot_react_app:${{ github.run_id }}

        docker push ${{ secrets.DOCKER_USERNAME }}/springboot_react_app:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/springboot_react_app:latest